server:
  port: 8001

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #,http://eureka7003.com:7003/eureka/
    fetch-registry: true
  instance:
    instance-id: cloud-provider-payment8001
    prefer-ip-address: true     #访问路径可以显示IP地址

spring:
  application:
    name: cloud-provider-hystrix-payment